ASESORES = [
    "Hugo Enrique Pérez Ramírez",
    "José Alvaro Martínez Espejel",
    "Carlos Iván Lara Mendoza",
    "Mauricio Gutiérrez Pérez Palma",
]

GIROS_NEGOCIO = [
    # Sector Primario (Agro y Extractivo)
    "Agricultura de granos y semillas",
    "Cultivo de frutales y nueces",
    "Cultivo de hortalizas",
    "Ganadería bovina",
    "Ganadería porcina",
    "Avicultura",
    "Apicultura",
    "Pesca y captura",
    "Acuicultura",
    "Silvicultura y tala",
    "Minería de metales preciosos (oro, plata)",
    "Minería de minerales metálicos industriales",
    "Extracción de petróleo y gas",
    "Extracción de materiales pétreos (canteras)",
    
    # Sector Secundario (Industria y Manufactura)
    "Industria Automotriz (Ensamblaje)",
    "Manufactura de Autopartes",
    "Industria Aeroespacial",
    "Construcción residencial",
    "Construcción de infraestructura y obra pública",
    "Industria Alimentaria",
    "Elaboración de bebidas alcohólicas (Cerveza, Tequila, Mezcal, Vinos)",
    "Elaboración de bebidas no alcohólicas",
    "Industria Tabacalera",
    "Fabricación de insumos textiles",
    "Confección de prendas de vestir",
    "Fabricación de calzado",
    "Industria del cuero y piel",
    "Industria Maderera",
    "Fabricación de papel y celulosa",
    "Imprenta e industrias conexas",
    "Refinación de petróleo",
    "Industria Química",
    "Fabricación de farmacéuticos y medicinas",
    "Fabricación de pinturas y recubrimientos",
    "Industria del plástico y hule",
    "Fabricación de vidrio y productos de vidrio",
    "Fabricación de cemento y concreto",
    "Siderurgia (Hierro y Acero)",
    "Fabricación de productos metálicos",
    "Fabricación de maquinaria y equipo",
    "Fabricación de equipo de computación y periféricos",
    "Fabricación de equipos de comunicación",
    "Fabricación de accesorios eléctricos",
    "Fabricación de muebles",
    "Fabricación de juguetes",
    "Maquiladora de exportación",
    
    # Sector Terciario (Comercio)
    "Comercio al por mayor de alimentos",
    "Comercio al por mayor de materias primas",
    "Comercio al por mayor de maquinaria",
    "Supermercados y tiendas de autoservicio",
    "Tiendas departamentales",
    "Comercio al por menor de ropa y accesorios",
    "Farmacias y droguerías",
    "Tiendas de conveniencia",
    "Comercio electrónico (E-commerce)",
    "Ferreterías y tlapalerías",
    "Venta de vehículos nuevos y usados",
    "Refaccionarias automotrices",
    "Comercio de artículos de papelería",
    "Comercio de electrodomésticos",
    
    # Sector Terciario (Servicios)
    "Transporte aéreo",
    "Transporte ferroviario",
    "Transporte marítimo y de carga",
    "Autotransporte de carga federal",
    "Transporte urbano y suburbano",
    "Mensajería y paquetería",
    "Almacenamiento y logística",
    "Servicios de telecomunicaciones (ISP, Telefonía)",
    "Banca comercial",
    "Banca de inversión",
    "Cajas de ahorro y crédito",
    "Compañías de seguros y fianzas",
    "Casas de bolsa",
    "Fintech",
    "Arrendamiento de bienes inmuebles",
    "Agencias inmobiliarias",
    "Servicios legales y jurídicos",
    "Contabilidad y auditoría",
    "Consultoría en administración",
    "Arquitectura e ingeniería",
    "Diseño gráfico e industrial",
    "Investigación y desarrollo científico",
    "Agencias de publicidad y marketing",
    "Servicios de limpieza y mantenimiento",
    "Seguridad privada y vigilancia",
    "Servicios de empleo y recursos humanos",
    "Agencias de viajes y operadores turísticos",
    
    # Educación y Salud
    "Escuelas de educación básica",
    "Universidades e instituciones de educación superior",
    "Escuelas de idiomas y capacitación técnica",
    "Consultorios médicos",
    "Hospitales y sanatorios",
    "Laboratorios clínicos",
    "Asilos y residencias para el cuidado de ancianos",
    "Guarderías",
    
    # Turismo y Entretenimiento
    "Hoteles y moteles",
    "Restaurantes y servicios de preparación de alimentos",
    "Bares, cantinas y centros nocturnos",
    "Servicios de catering y banquetes",
    "Cines y producción cinematográfica",
    "Museos y sitios históricos",
    "Gimnasios y centros deportivos",
    "Parques de diversiones",
    "Casinos y juegos de azar",
    
    # Tecnología (Sector Cuaternario)
    "Desarrollo de software",
    "Servicios de computación en la nube (SaaS, IaaS)",
    "Procesamiento de datos y hosting",
    "Ciberseguridad",
    "Inteligencia Artificial y Robótica",
    "Blockchain y Criptoactivos",
    "Desarrollo de videojuegos",
    
    # Otros Servicios
    "Reparación y mantenimiento automotriz",
    "Reparación de equipo electrónico",
    "Servicios funerarios",
    "Lavanderías y tintorerías",
    "Estéticas y salones de belleza",
    "Asociaciones y organizaciones civiles (ONGs)"
]