[client]
showErrorDetails = "none"

[server]
enableStaticServing = true

[theme]
base = "light"
primaryColor = "#003057"
backgroundColor = "#f2f3f0"
secondaryBackgroundColor = "rgb(255, 255, 255)"

font = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
baseFontSize = 16
baseFontWeight = 400
headingFont = "Inter:https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&display=swap"
headingFontSizes = ["2.5rem", "2rem", "1.75rem"]
headingFontWeights = [700, 600, 500]
# codeFont = "Fira Code"
# codeFontSize = "0.8rem"
baseRadius = "small"
buttonRadius = "large"
# dataframeBorderColor
# dataframeBorderColor
dataframeHeaderBackgroundColor = "#f0f0f0ff"